export const dexToNameLabel = {
    "national": "National", 
    "kanto": "Kanto", 
    "original-johto": "Gold/Silver/Crystal Johto", 
    "hoenn": "Ruby/Sapphire/Emerald Hoenn", 
    "original-sinnoh": "Diamond/Pearl Sinnoh", 
    "extended-sinnoh": "Platinum Sinnoh", 
    "updated-johto": "HeartGold/SoulSilver Johto",
    "original-unova": "Black/White Unova", 
    "updated-unova": "Black 2/White 2 Unova", 
    "kalos-central": "Kalos Central", 
    "kalos-coastal": "Kalos Coastal",
    "kalos-mountain": "Kalos Mountain", 
    "updated-hoenn": "Omega Ruby/Alpha Sapphire Hoenn",
    "original-alola": "Sun/Moon Alola",
    "original-melemele": "Sun/Moon Melemele",
    "original-akala": "Sun/Moon Akala", 
    "original-ulaula": "Sun/Moon Ulaula", 
    "original-poni": "Sun/Moon Poni", 
    "updated-alola": "Ultra Sun/Ultra Moon Alola",
    "updated-melemele": "Ultra Sun/Utlra Moon Melemele",
    "updated-akala": "Ultra Sun/Utlra Moon Akala", 
    "updated-ulaula": "Ultra Sun/Utlra Moon Ulaula", 
    "updated-poni": "Ultra Sun/Utlra Moon Poni", 
    "letsgo-kanto": "Let's Go Kanto",
    "galar": "Galar", 
    "isle-of-armor": "Isle of Armor",
    "crown-tundra": "Crown Tundra",
    "hisui": "Legends: Arceus Hisui", 
    "paldea": "Paldea",
    "kitakami": "Kitakami",
    "blueberry": "Blueberry"
}