export const versionGroupAbr = {
    "red-blue": "R/B",
    "yellow": "Y",
    "gold-silver": "G/S",
    "crystal": "C",
    "ruby-sapphire": "R/S",
    "emerald": "E",
    "firered-leafgreen": "FR/LG",
    "diamond-pearl": "D/P",
    "platinum": "Pt",
    "heartgold-soulsilver": "HG/SS",
    "black-white": "B/W",
    "black-2-white-2": "B2/W2",
    "x-y": "X/Y",
    "omega-ruby-alpha-sapphire": "OR/AS",
    "sun-moon": "S/M",
    "ultra-sun-ultra-moon": "US/UM",
    "lets-go-pikachu-lets-go-eevee": "P/E",
    "sword-shield": "Sw/Sh",
    "brilliant-diamond-and-shining-pearl": "BD/SP",
    "legends-arceus": "LA",
    "scarlet-violet": "S/V",
}

export const versionGroupFull = {
    "red-blue": "Red/Blue",
    "yellow": "Yeloow",
    "gold-silver": "Gold/Silver",
    "crystal": "Crystal",
    "ruby-sapphire": "Ruby/Sapphire",
    "emerald": "Emerald",
    "firered-leafgreen": "FireRed/LeafGreen",
    "diamond-pearl": "Diamond/Pearl",
    "platinum": "Platinum",
    "heartgold-soulsilver": "HeartGold/SoulSilver",
    "black-white": "Black/White",
    "black-2-white-2": "Black 2/White 2",
    "x-y": "X/Y",
    "omega-ruby-alpha-sapphire": "Omega Ruby/Alpha Sapphire",
    "sun-moon": "Sun/Moon",
    "ultra-sun-ultra-moon": "Ultra Sun/Ultra Moon",
    "lets-go-pikachu-lets-go-eevee": "Let's Go Pikachu/Let's Go Eevee",
    "sword-shield": "Sword/Shield",
    "brilliant-diamond-and-shining-pearl": "Brilliant Diamond/Shining Pearl",
    "legends-arceus": "Legends Arceus",
    "scarlet-violet": "Scarlet/Violet",
}