export const versionGroupAbr = {
    "red-blue": "R/B",
    "yellow": "Y",
    "gold-silver": "G/S",
    "crystal": "C",
    "ruby-sapphire": "R/S",
    "emerald": "E",
    "firered-leafgreen": "FR/LG",
    "diamond-pearl": "D/P",
    "platinum": "Pt",
    "heartgold-soulsilver": "HG/SS",
    "black-white": "B/W",
    "black-2-white-2": "B2/W2",
    "x-y": "X/Y",
    "omega-ruby-alpha-sapphire": "OR/AS",
    "sun-moon": "S/M",
    "ultra-sun-ultra-moon": "US/UM",
    "lets-go-pikachu-lets-go-eevee": "P/E",
    "sword-shield": "Sw/Sh",
    "brilliant-diamond-and-shining-pearl": "BD/SP",
    "legends-arceus": "LA",
    "scarlet-violet": "S/V",
}